logging:
  level:
    com.eugenepelipets.popcornlist: DEBUG

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:file:./db/popcorn-list
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

server:
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force-request: true
      force-response: true

  tomcat:
    uri-encoding: UTF-8